### PR TITLE
Fix bug where saving state wouldn't be reported accurately to room participants + refactor editor return statement (does the same thing, but looks better)

### LINKED ISSUE #2369: Saving state not accurately reported to room participant that is not the host
To reproduce:
1. Make a shareable room on the beta editor
2. Open that room in a different browser with a different account
3. Make changes and observe that it permanently says saved to host, instead of saying saving...

### PR DESCRIPTION
**Pull request by Cosmin-Mare**
fixes #2369

### CODE REVIEW

File: src/components/big-interactive-pages/editor.tsx [hunk 1]
```diff
@@ -522,236 +522,240 @@ export default function Editor({ persistenceState, cookies, roomState }: EditorP
...
+			<div class={styles.pageMain}>
+				<div className={styles.codeContainer}>
+					<CodeMirror
+						persistenceState={persistenceState}
+						roomState={roomState}
+						class={styles.code}
+						initialCode={initialCode}
+						onEditorView={(editor) => {
+							codeMirror.value = editor;
+							setTimeout(() => foldAllTemplateLiterals(), 100); // Fold after the document is parsed (gross)
```
Comment (grymmy) [inline src/components/big-interactive-pages/editor.tsx:546]: What necessitates folding the template literals to begin with?  I don't argue against needing to, just looking to understand (it's probably best to state this explicitly in the comment, tbh)

File: src/components/big-interactive-pages/editor.tsx [hunk 2]
```diff
@@ -522,236 +522,240 @@ export default function Editor({ persistenceState, cookies, roomState }: EditorP
...
+								);
+							}}
+						/>
+						<div
+							class={styles.helpContainer}
+							// style={{ height: realHelpAreaSize.value, maxHeight: outputArea.current?.clientHeight! - (screenControls.current?.clientHeight! + screenContainer.current?.clientHeight!) }}
+							style={{ height: realHelpAreaSize.value, maxHeight: outputArea.current?.clientHeight! - (screenContainer.current?.clientHeight! - screenControls.current?.clientHeight!) }}
+						>
+							{!(
+								(persistenceState.value.kind === PersistenceStateKind.SHARED ||
```
Comment (grymmy) [inline src/components/big-interactive-pages/editor.tsx:697]: It really does seem like there are a multitude of these checks which probably could be collapsed into one or several utility methods to make the code more readable and less prone to making a copy/paste or logic error.

**Review by grymmy — CHANGES_REQUESTED** [review]
plz at least add requested commentary - bonus points if u could expend some effort to clean up duplicate persistentState code

File: src/components/big-interactive-pages/editor.tsx (hunk 1 above)
Comment (Cosmin-Mare) [reply src/components/big-interactive-pages/editor.tsx:546]: that was done by someone else b4 my changes. it's probabyl because every template literal starts up as unfolded by default

File: src/components/big-interactive-pages/editor.tsx (hunk 2 above)
Comment (grymmy) [reply src/components/big-interactive-pages/editor.tsx:697]: okay but actually plz do follow up on it

File: src/components/big-interactive-pages/editor.tsx (hunk 1 above)
Comment (grymmy) [reply src/components/big-interactive-pages/editor.tsx:546]: okay - just make sure any refactorings you might do don't break any of this stuff :)

**Review by grymmy — APPROVED** [review]

File: src/components/big-interactive-pages/editor.tsx (hunk 1 above)
Comment (Cosmin-Mare) [reply src/components/big-interactive-pages/editor.tsx:546]: yup, most of the highlighted lines were just tabs

File: src/components/big-interactive-pages/editor.tsx (hunk 2 above)
Comment (Cosmin-Mare) [reply src/components/big-interactive-pages/editor.tsx:697]: 🫡
