### PR TITLE
Purge @img tag for all games

### LINKED ISSUE #1579: Image metadata is deprecated?
**Describe the bug**
All games on Sprig have a few metadata properties (i.e. `@title`, `@author`) and one of them is `@img`. After investigating some games that in the img property used "filename.png", I noticed the web browser make a call to `/gallery/game.png`. That however points to the gallery editor and the img itself. After looking more into the source code I located that the image source is now loaded via the already existing sprig API.

**To Reproduce**
1. Go to 'https://sprig.hackclub.com/gallery'
2. Check Vercel/Console log
3. Notice the error about `filename.png`

**Expected behavior**
The game img loads normally without any errors

**Actual behavior**  
The game img loads normally but games with the specified `@img` tag point to bad path.

**Solution**
The solution is rather easy:
```[tasklist]
- [ ] Remove the src attribute from the gallery.tsx
- [ ] Remove the `@img` tag from the template
- [ ] Edit metadata generate hook to not use `@img`
- [ ] Mass remove all mentions `@img` from games
```

**Screenshots**
image
image
image

### PR DESCRIPTION
**Pull request by GalaxyGamingBoy**
closes #1579

### CODE REVIEW

File: src/pages/gallery/gallery.tsx [hunk 1]
```diff
@@ -252,7 +252,6 @@ export default function Gallery({ games, tags }: { games: GameMetadata[], tags:
 							) : null}
 
 							<img
-								src={`gallery/${game.img}`}
```
Comment (JosiasAurel) [inline src/pages/gallery/gallery.tsx:255]: why delete this? will images still show up in gallery?

**Review by JosiasAurel — CHANGES_REQUESTED** [review]

File: src/pages/gallery/gallery.tsx (hunk 1 above)
Comment (GalaxyGamingBoy) [reply src/pages/gallery/gallery.tsx:255]: Yep, as stated in #1579 and with the following code block, we can determine that the image data is now injected via base64 on the loadThumbnail function as to a png. The png link errors because it points to the game editor. We can also verify it using the vercel preview.
https://github.com/hackclub/sprig/blob/main/src/pages/gallery/gallery.tsx#L108-L116

**Review by grymmy — APPROVED** [review]

**Comment by grymmy** [comment]
@GalaxyGamingBoy before landing plz look at the plagiarism checker and test-game action failures

**Comment by grymmy** [comment]
@JosiasAurel sorry - I tried looking at your requested changes here but the large # of files made it - for one reason or another - somewhat difficult to understand the changes you want on this diff - can u plz ELI5 for me (I am almost definitely missing something)

**Comment by GalaxyGamingBoy** [comment]
> @GalaxyGamingBoy before landing plz look at the plagiarism checker and test-game action failures

Already done w/ Josias, the plagiarism one only works on a single file and the other test failed - because of an error on one game,

**Comment by JosiasAurel** [comment]
> @JosiasAurel sorry - I tried looking at your requested changes here but the large # of files made it - for one reason or another - somewhat difficult to understand the changes you want on this diff - can u plz ELI5 for me (I am almost definitely missing something)

the majority of the files applied the changes. I wanted to make sure that removing the src property on the img tag won't break anything and it hasn't as far as i can tell

**Comment by JosiasAurel** [comment]
please resolve conflicts and we can merge!

**Review by JosiasAurel — APPROVED** [review]
lgtm
