### PR TITLE
Fix bug where room participants wouldn't update

### LINKED ISSUE #2419: Participant count of room doesn't increase

### PR DESCRIPTION
**Pull request by Cosmin-Mare**
fixes #2419

### CODE REVIEW

**Review by grymmy — APPROVED** [review]
Would appreciate addition of a singular comment to explain what you're doing here in layperson's terms.

File: src/components/codemirror.tsx [hunk 1]
```diff
@@ -181,6 +181,21 @@ export default function CodeMirror(props: CodeMirrorProps) {
...
+			provider.awareness.on("update", () => {
+				let participants: RoomParticipant[] = [];
+				provider.awareness.getStates().forEach((state) => {
+					try{
+						participants.push({
+							userEmail: state.user.name,
+							isHost: state.user.host
+						})
+					} catch(e){
+						return
```
Comment (grymmy) [inline src/components/codemirror.tsx:193]: is it OK for this to be very quietly failing w/o any logging?

Comment (Cosmin-Mare) [reply src/components/codemirror.tsx:193]: yup. bc that means that the participant doesn't have an email, therefore it's the saving instance and we don't count that towards the participants
